header:
  version: 10

machine: raspberrypi5
distro: poky
target:
  - update-image
repos:
  poky:
    url: https://git.yoctoproject.org/git/poky
    path: poky
    branch: scarthgap
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-raspberrypi:
    url: https://github.com/raspberrypi/meta-raspberrypi
    path: meta-raspberrypi
    branch: scarthgap

  meta-lts-mixins:
    path: meta-lts-mixins
  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    path: layers/meta-openembedded
    branch: scarthgap
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-perl:

  meta-swupdate:
    url: https://github.com/sbabic/meta-swupdate
    branch: scarthgap
  meta-swupdate-boards:
    url: https://github.com/sbabic/meta-swupdate-boards
    branch: scarthgap
  meta-berge:
    path: meta-berge

local_conf_header:
  custom: |
    RPI_USE_U_BOOT = "1"
    DISABLE_RPI_BOOT_LOGO = "1"
    ENABLE_UART = "1"
    UBOOT_MACHINE:raspberrypi5 = "rpi_arm64_defconfig"
    SERIAL_CONSOLES = "115200;ttyAMA0"
    EXTRA_IMAGE_FEATURES += "debug-tweaks"
    IMAGE_INSTALL:append = " openssh openssh-sftp-server avahi-daemon libgcc vim htop swupdate swupdate-www etc-overlay "
    DISTRO_FEATURES:append = " systemd usrmerge"
    VIRTUAL-RUNTIME_init_manager = "systemd"
    IMAGE_FSTYPES:append = " ext4.gz wic.bz2"
    WKS_FILE = "ts-raspberrypi.wks"
